404 newhomepage
WebJamApps/JaMmusic pull request #939
Opened 2023-07-21 14:58 UTC by kathleenahall

2023-11-03 19:43 UTC, JoshuaVSherman requested changes
@kathleenahall there are issues with various screens sizes and cellphone display to fix please

2024-01-30 12:07 UTC, JoshuaVSherman commented
@kathleenahall is this pull request any good still, i see you now have a new pull request with a different branch?

2024-01-30 15:45 UTC, kathleenahall commented
I wasn't sure if I should make a new branch. I can merge them

On Tue, Jan 30, 2024, 07:07 Joshua V Sherman ***@***.***>
wrote:

> @kathleenahall <https://github.com/kathleenahall> is this pull request
> any good still, i see you now have a new pull request with a different
> branch?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WebJamApps/JaMmusic/pull/939#issuecomment-1916701082>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2ENYXFRI32D4WRSKA4X2M3YRDO7VAVCNFSM6AAAAAA2S6QHBKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMJWG4YDCMBYGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-27 12:49 UTC, JoshuaVSherman commented
@kathleenahall is this ready for me to review/test locally now?

2024-02-29 13:02 UTC, JoshuaVSherman requested changes

2024-02-29 13:02 UTC, JoshuaVSherman commented on test/containers/Homepage/Widescreen/index.spec.tsx
> +  //   const homepage = renderer.create(<NewHomepage />).toJSON();
please delete commented out code in this file

2024-03-05 12:33 UTC, JoshuaVSherman approved these changes

2024-03-05 12:33 UTC, merged